[tool.poetry]
name = "vn-open-api-provinces"
version = "0.2.0"
description = ""
authors = ["Nguyễn Hồng Quân <ng.hong.quan@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.70.0"
pydantic = "^1.8.2"
Logbook = "^1.5.3"
vietnam-provinces = "^0.4.2"
uvicorn = "^0.15.0"
fastapi-rfc7807 = "^0.5.0"
aiofiles = "^0.8.0"
lunr = "^0.6.1"
Unidecode = "^1.3.2"
single-version = "^1.5.1"

[tool.poetry.dev-dependencies]
doc8 = "^0.8.1"
flake8 = "^3.9.2"
wheel = "^0.37.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
