[tool.poetry]
name = "vn-open-api-provinces"
version = "0.1.0"
description = ""
authors = ["Nguyễn Hồng Quân <ng.hong.quan@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6.1"
fastapi = "^0.66.0"
pydantic = "^1.8.2"
Logbook = "^1.5.3"
vietnam-provinces = "^0.4.2"
uvicorn = "^0.14.0"
dataclasses = { version = "^0.8", markers = "python_version < '3.7'" }
fastapi-rfc7807 = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
doc8 = "^0.8.1"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
